feat: added test for dio
jhomlala/alice pull request #223
Opened 2024-07-05 06:50 UTC by jhomlala

2024-07-05 20:10 UTC, techouse requested changes

2024-07-05 20:10 UTC, techouse commented on packages/alice_dio/test/alice_dio_adapter_test.dart
> +      await dio.get<void>('https://httpbin.org/json',
You'll need to mock this. Network calls are not allowed from a test. Check how we do it in Chopper https://github.com/lejard-h/chopper/blob/33372bf395977f20bf0184d8c3b9deb07656461a/chopper/test/client_test.dart#L24

2024-07-07 12:11 UTC, jhomlala commented
@techouse I think you can revisit it again. It's still in draft, but It's almost there.

2024-07-07 17:34 UTC, techouse approved these changes
LGTM

2024-07-07 18:59 UTC, merged